name: barcode_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.3

environment:
  sdk: ^3.4.0

dependencies:
  barcode_scan2: ^4.3.3
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  sqflite: ^2.3.3+2
  table_calendar: ^3.1.2
  flutter_launcher_icons: ^0.9.2
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
